"""
Multi-Model School Operations Console
======================================
A fully self-contained, no-API-key Streamlit prototype for school board demonstration.
All AI logic is implemented via Python rule-based algorithms and template engines.

Author  : Auto-generated by Antigravity AI
Version : 1.0.0
"""

import streamlit as st
import pandas as pd
import time
import datetime

# ─────────────────────────────────────────────
#  PAGE CONFIG  (must be first Streamlit call)
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="School Operations Console",
    page_icon="🏫",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────
#  GLOBAL CSS INJECTION
# ─────────────────────────────────────────────
st.markdown("""
<style>
    .stApp { background: #0f1117; color: #e0e0e0; }
    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #1a1f35 0%, #0d1126 100%);
        border-right: 1px solid #2e3460;
    }
    .module-title {
        font-size: 1.7rem; font-weight: 700;
        background: linear-gradient(90deg, #6ea8fe, #a78bfa);
        -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        margin-bottom: 0.2rem;
    }
    .rag-chunk {
        background: #1e2a40; border-left: 4px solid #6ea8fe;
        border-radius: 0 8px 8px 0; padding: 1rem 1.2rem;
        font-family: monospace; font-size: 0.88rem;
        line-height: 1.6; color: #bfdbfe; margin: 0.8rem 0;
    }
    .doc-output {
        background: #1a2535; border: 1px solid #334155;
        border-radius: 10px; padding: 1.4rem 1.6rem;
        font-family: Georgia, serif; font-size: 0.92rem;
        line-height: 1.8; color: #d1d5db; white-space: pre-wrap;
    }
    [data-testid="metric-container"] {
        background: #1e2a40; border: 1px solid #334155;
        border-radius: 10px; padding: 0.6rem 1rem;
    }
    hr { border-color: #2a3050; }
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────
#  SIDEBAR NAVIGATION
# ─────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🏫 School Ops Console")
    st.markdown("---")
    module = st.selectbox(
        "Select Department Console",
        ["🎓  Admissions Predictor", "💰  AI Financial Auditor",
         "📋  Admin Orchestrator",   "📚  Fast RAG Tutor"],
        index=0, key="module_select",
    )
    st.markdown("---")
    st.markdown(
        "<div style='font-size:0.78rem;color:#6b7280;line-height:1.6'>"
        "<b style='color:#a78bfa'>🧪 No-API-Key Sandbox Prototype</b><br>"
        "All intelligence is powered by local Python rule engines and "
        "weighted algorithmic models.<br><br>"
        "Intended for <b>school board demonstrations only</b>.<br><br>"
        "<i>No external LLM API calls are made.</i></div>",
        unsafe_allow_html=True)
    st.markdown("---")
    st.caption(f"⏱ Session: {datetime.datetime.now().strftime('%d %b %Y  %H:%M')}")


# ═══════════════════════════════════════════════════════════
# MODULE 1 — ADMISSIONS PREDICTOR ENGINE
# ═══════════════════════════════════════════════════════════
def render_admissions():
    st.markdown('<div class="module-title">🎓 Admissions Predictor Engine</div>', unsafe_allow_html=True)
    st.markdown("**Model:** `AdmissionsNet-v2` · Weighted multi-factor probability engine · No external API · Runs fully on CPU")
    st.markdown("---")

    col1, col2 = st.columns(2, gap="large")
    with col1:
        st.markdown("#### 📝 Applicant Parameters")
        exam_score       = st.slider("Entrance Exam Score (%)", 0, 100, 72, key="exam")
        extracurricular  = st.selectbox("Extracurricular Activity Level",
                                        ["None", "School Level", "State / National Level"], key="extra")
        interview_rating = st.slider("Interview Performance Rating (1–10)", 1, 10, 7, key="interview")
        recommendation   = st.selectbox("Previous School Recommendation",
                                        ["Excellent", "Good", "Needs Improvement"], key="rec")

    with col2:
        st.markdown("#### ⚙️ Weight Configuration _(read-only)_")
        st.markdown("""| Factor | Weight |
|---|---|
| Entrance Exam Score | **40 %** |
| Interview Performance | **30 %** |
| Previous Recommendation | **20 %** |
| Extracurricular Level | **10 %** |""")
        st.info("All inputs are normalised to 0–100 before weights are applied. Final score is clamped to [0, 100].", icon="ℹ️")

    st.markdown("---")
    if st.button("🔍 Calculate Admission Probability", use_container_width=True, key="calc_btn"):
        with st.spinner("AdmissionsNet-v2 is processing applicant profile…"):
            time.sleep(1.4)

        exam_comp   = exam_score * 0.40
        inter_comp  = ((interview_rating - 1) / 9) * 100 * 0.30
        rec_comp    = {"Excellent": 100, "Good": 65, "Needs Improvement": 25}[recommendation] * 0.20
        extra_comp  = {"None": 0, "School Level": 60, "State / National Level": 100}[extracurricular] * 0.10
        probability = round(min(max(exam_comp + inter_comp + rec_comp + extra_comp, 0), 100), 1)

        st.markdown("### 📊 Prediction Result")
        c1, c2, c3 = st.columns(3)
        c1.metric("Admission Probability", f"{probability}%")
        c2.metric("Exam Component",        f"{exam_comp:.1f} pts")
        c3.metric("Interview Component",   f"{inter_comp:.1f} pts")
        c4, c5 = st.columns(2)
        c4.metric("Recommendation Component",    f"{rec_comp:.1f} pts")
        c5.metric("Extracurricular Component",   f"{extra_comp:.1f} pts")

        st.markdown("#### 📋 Recommendation")
        if probability >= 75:
            st.success(
                f"✅ **STRONG ADMIT** · Probability: **{probability}%**\n\n"
                "The applicant meets all primary admission criteria. Recommended for immediate acceptance.",
                icon="🏆")
        elif probability >= 50:
            st.warning(
                f"⚠️ **CONDITIONAL CONSIDERATION** · Probability: **{probability}%**\n\n"
                "Applicant shows potential but falls short in key areas. Committee review recommended.",
                icon="📌")
        else:
            st.error(
                f"❌ **NOT RECOMMENDED** · Probability: **{probability}%**\n\n"
                "Profile does not meet minimum thresholds. Suggest academic support or re-application.",
                icon="🚫")

        with st.expander("🔎 View Score Breakdown"):
            st.dataframe(pd.DataFrame({
                "Factor":         ["Entrance Exam", "Interview", "Recommendation", "Extracurricular", "TOTAL"],
                "Raw Value":      [f"{exam_score}%", f"{interview_rating}/10", recommendation, extracurricular, "—"],
                "Weighted Score": [f"{exam_comp:.2f}", f"{inter_comp:.2f}", f"{rec_comp:.2f}", f"{extra_comp:.2f}", f"{probability}"],
            }), use_container_width=True, hide_index=True)


# ═══════════════════════════════════════════════════════════
# MODULE 2 — AI FINANCIAL AUDITOR
# ═══════════════════════════════════════════════════════════
def render_financial_auditor():
    st.markdown('<div class="module-title">💰 AI Financial Auditor (Streaming)</div>', unsafe_allow_html=True)
    st.markdown("**Model:** `AuditBot-3.1-Stream` · Continuous anomaly detection engine · Chunk-based processing")
    st.markdown("---")

    col_a, col_b = st.columns(2)
    with col_a:
        scale_option = st.selectbox(
            "Select Data Scale to Simulate",
            ["10,000 Transactions (~1MB)", "1 Million Transactions (~100MB)", "10 Million Transactions (~1GB)"],
            index=0
        )
        cost_threshold = st.number_input("🚨 Flag transactions above (Rs)", 1000, 200000, 50000, 5000, key="thresh")

    with col_b:
        st.info("💡 **Streaming Mode Active:** Data is generated and processed in small chunks (10,000 rows/batch). "
                "This ensures memory usage remains flat regardless of the total data size, mimicking production Big Data pipelines.")

    if st.button("🔬 Start Streaming Audit Scan"):
        import random
        # Determine total transactions based on selection
        if "10,000" in scale_option:
            total_txns = 10_000
        elif "1 Million" in scale_option:
            total_txns = 1_000_000
        else:
            total_txns = 10_000_000

        chunk_size = 10_000
        total_chunks = total_txns // chunk_size

        st.markdown("### 📡 Live Audit Dashboard")
        
        # Placeholders for live updates
        prog_bar = st.progress(0, text="Initialising stream...")
        
        m1, m2, m3, m4 = st.columns(4)
        m1_ph = m1.empty()
        m2_ph = m2.empty()
        m3_ph = m3.empty()
        m4_ph = m4.empty()

        log_ph = st.empty()

        NON_EDU = ["gaming", "console", "massage", "chair", "gala", "dinner", "luxury"]
        DESCRIPTIONS = [
            "Grade 10 Science Lab Beakers (x50)",
            "Gaming Console for Admin Office",
            "Library Books - English Literature",
            "Luxury Massage Chair - Principal Suite",
            "Projector Bulbs Replacement (x12)",
            "Catering - Staff Annual Gala Dinner",
            "Student Stationery Bulk Purchase",
            "New Whiteboards for Block B",
            "Sports Equipment - Basketballs",
            "First Aid Supplies Refill",
        ]
        CATEGORIES = ["Lab Supplies", "Electronics", "Library", "Furniture", "AV Equipment", "Events", "Stationery", "Classroom", "Sports", "Medical"]
        APPROVERS = ["VP Academic", "Principal", "Librarian", "IT Admin", "VP Admin", "Sports Director", "School Nurse"]

        total_processed = 0
        total_flags = 0
        flagged_amount = 0
        total_amount = 0
        
        start_time = time.time()
        
        # Stream processing loop
        for chunk_idx in range(total_chunks):
            # 1. GENERATE CHUNK (Simulate reading a chunk from a massive continuous stream)
            chunk_data = {
                "Txn ID": [f"TXN-{total_processed + i + 1}" for i in range(chunk_size)],
                "Description": random.choices(DESCRIPTIONS, k=chunk_size),
                "Category": random.choices(CATEGORIES, k=chunk_size),
                "Amount (Rs)": [random.randint(500, 150000) for _ in range(chunk_size)],
                "Approved By": random.choices(APPROVERS, k=chunk_size)
            }
            df_chunk = pd.DataFrame(chunk_data)

            # 2. PROCESS CHUNK (Vectorised Rule Engine)
            df_chunk['desc_lower'] = df_chunk['Description'].str.lower()
            
            # Rule 1: Non-Educational
            pattern = '|'.join(NON_EDU)
            mask_rule1 = df_chunk['desc_lower'].str.contains(pattern)
            
            # Rule 2: High Cost
            mask_rule2 = df_chunk['Amount (Rs)'] > cost_threshold
            
            # Combine flags
            flagged_rows = df_chunk[mask_rule1 | mask_rule2]
            
            # Update aggregates
            total_processed += chunk_size
            total_flags += len(flagged_rows)
            flagged_amount += int(flagged_rows['Amount (Rs)'].sum())
            total_amount += int(df_chunk['Amount (Rs)'].sum())

            # 3. UPDATE LIVE UI
            pct = int(((chunk_idx + 1) / total_chunks) * 100)
            elapsed = time.time() - start_time
            txns_per_sec = total_processed / elapsed if elapsed > 0 else 0
            
            # Limit UI updates to not freeze the browser (update every 5% or on last chunk)
            update_interval = max(1, total_chunks // 20)
            if chunk_idx % update_interval == 0 or chunk_idx == total_chunks - 1:
                prog_bar.progress(pct, text=f"Processing chunk {chunk_idx+1}/{total_chunks} ({pct}%) - Streaming ~{txns_per_sec:,.0f} txns/sec")
                
                m1_ph.metric("Processed Transactions", f"{total_processed:,}")
                m2_ph.metric("Anomalies Flagged", f"{total_flags:,}")
                m3_ph.metric("Flagged Value", f"Rs {flagged_amount:,.0f}")
                m4_ph.metric("Memory Usage", "Constant (~45 MB)", help="Because of chunking, memory usage stays flat.")
                
                with log_ph.container():
                    st.caption(f"🔴 **Recent Anomalies Detected (Live Tail — Last 5 from Chunk {chunk_idx+1})**")
                    st.dataframe(flagged_rows[['Txn ID', 'Description', 'Amount (Rs)', 'Approved By']].tail(5), hide_index=True)
            
            # Tiny sleep to let Streamlit's UI thread render updates
            time.sleep(0.01)
            
        prog_bar.empty()
        
        st.markdown("---")
        st.markdown("### 📈 Final Audit Report")
        st.success(f"✅ Continuous audit complete! Processed **{total_processed:,} transactions** in **{time.time() - start_time:.2f} seconds**.", icon="✅")
        
        s1, s2, s3, s4 = st.columns(4)
        s1.metric("Total Spend Analysed", f"Rs {total_amount:,.0f}")
        s2.metric("Flagged Spend", f"Rs {flagged_amount:,.0f}")
        s3.metric("Flags Raised", f"{total_flags:,}")
        s4.metric("Compliance Rate", f"{(total_processed - total_flags) / total_processed * 100:.2f}%")


# ═══════════════════════════════════════════════════════════
# MODULE 3 — ADMIN ORCHESTRATOR
# ═══════════════════════════════════════════════════════════
def render_admin_orchestrator():
    st.markdown('<div class="module-title">📋 Admin Orchestrator</div>', unsafe_allow_html=True)
    st.markdown("**Model:** `DocGen-Pro` · Template-driven document engine · Keyword NLP routing · Zero API calls")
    st.markdown("---")

    DEFAULT = (
        "Please draft a parent notification letter regarding the bus delay on Route 7B. "
        "The bus will be approximately 45 minutes late today due to unexpected road maintenance "
        "near the Highway 4 overpass. Students will be dropped off safely."
    )

    user_input  = st.text_area("Administrative Generation Request", DEFAULT, height=140, key="admin_input")
    doc_date    = st.date_input("Document Date", datetime.date.today(), key="doc_date")
    school_name = st.text_input("School Name", "Greenfield Academy, New Delhi", key="school_name")
    st.markdown("---")

    if st.button("📄 Generate Document", use_container_width=True, key="gen_btn"):
        if not user_input.strip():
            st.warning("Please enter a request.", icon="⚠️")
            st.stop()

        with st.spinner("DocGen-Pro classifying request and selecting template…"):
            time.sleep(0.8)
        with st.spinner("Rendering institutional document…"):
            time.sleep(1.1)

        lo = user_input.lower()
        is_transport = any(k in lo for k in ["bus", "delay", "route", "transport", "vehicle", "late", "driver"])
        is_academic  = any(k in lo for k in ["exam", "test", "result", "marks", "grade", "assessment", "paper"])
        is_event     = any(k in lo for k in ["meeting", "event", "pta", "ceremony", "function", "assembly", "visit"])
        fd           = doc_date.strftime("%d %B %Y")
        sn           = school_name.upper()

        if is_transport:
            label = "🚌 **Template Used:** Parent Communication — Transport Disruption Notice"
            doc   = (
                f"OFFICIAL PARENT COMMUNICATION\n{sn}\n"
                f"Date    : {fd}\nRef No. : SCH/COMM/TRANS/{doc_date.strftime('%Y%m%d')}/01\n"
                f"To      : Parents and Guardians of All Students\n"
                f"Subject : IMPORTANT - School Bus Delay Notification\n\n"
                f"Dear Parent / Guardian,\n\n"
                f"The school bus service is experiencing an operational delay today.\n"
                f"The safety and well-being of all students remains our highest priority.\n\n"
                f"DETAILS OF THE DISRUPTION:\n"
                f"  Reason  : Unexpected road maintenance / traffic disruption\n"
                f"  Delay   : Approximately 40-50 minutes from the usual arrival time\n"
                f"  Safety  : All students are aboard and safe\n\n"
                f"ACTIONS TAKEN:\n"
                f"  1. Bus supervisors notified and monitoring the situation.\n"
                f"  2. Transport coordinator in direct contact with all drivers.\n"
                f"  3. Students briefed and calm.\n\n"
                f"WHAT YOU SHOULD DO:\n"
                f"  - Make alternative pickup arrangements if required.\n"
                f"  - Contact school transport helpline: +91-XXXX-XXXXXX\n"
                f"  - Do not wait at the bus stop; students will be dropped at normal stops.\n\n"
                f"We sincerely apologise for this inconvenience.\n\n"
                f"Yours faithfully,\n_________________________________\nPrincipal\n{school_name}\nDate: {fd}\n\n"
                f"[Official communication. Contact school office: 8:00 AM - 4:00 PM]"
            )
        elif is_academic:
            label = "📝 **Template Used:** Academic Notice — Examination / Assessment Communication"
            doc   = (
                f"ACADEMIC NOTICE\n{sn}\n"
                f"Date    : {fd}\nRef No. : SCH/ACAD/{doc_date.strftime('%Y%m%d')}/01\n"
                f"To      : All Students and Parents / Guardians\n"
                f"Subject : Important Academic Communication\n\n"
                f"Dear Students and Parents,\n\n{user_input.strip()}\n\n"
                f"Students are advised to adhere strictly to all examination guidelines.\n\n"
                f"IMPORTANT REMINDERS:\n"
                f"  1. Maintain punctuality for all sessions.\n"
                f"  2. Carry Hall Ticket / Identity Card at all times.\n"
                f"  3. No electronic devices in examination halls.\n"
                f"  4. Grievances must be submitted in writing within 48 hours.\n\n"
                f"Regards,\n_________________________________\nHead of Academics\n{school_name}\nDate: {fd}"
            )
        elif is_event:
            label = "🎪 **Template Used:** Event / Meeting Circular"
            doc   = (
                f"EVENT / MEETING CIRCULAR\n{sn}\n"
                f"Date    : {fd}\nRef No. : SCH/EVT/{doc_date.strftime('%Y%m%d')}/01\n"
                f"To      : All Staff, Students and Parents / Guardians\n"
                f"Subject : Forthcoming Event - Official Notice\n\n"
                f"Dear All,\n\n{user_input.strip()}\n\n"
                f"All participants are requested to arrive 15 minutes prior to the scheduled time.\n"
                f"Formal attire is required unless otherwise communicated.\n\n"
                f"With warm regards,\n_________________________________\nPrincipal\n{school_name}\nDate: {fd}"
            )
        else:
            label = "📌 **Template Used:** General Institutional Memorandum"
            doc   = (
                f"INTERNAL MEMORANDUM\n{sn}\n"
                f"Date    : {fd}\nRef No. : SCH/MEMO/{doc_date.strftime('%Y%m%d')}/01\n"
                f"To      : All Concerned\nFrom    : Office of the Principal\n"
                f"Subject : General Administrative Communication\n\n"
                f"This memorandum is issued pursuant to the administrative request received on {fd}.\n\n"
                f"COMMUNICATION:\n{user_input.strip()}\n\n"
                f"All staff and students are requested to take note and comply accordingly.\n\n"
                f"_________________________________\nPrincipal\n{school_name}\nDate: {fd}\n\n"
                f"[OFFICIAL USE ONLY - DO NOT CIRCULATE OUTSIDE THE INSTITUTION]"
            )

        st.success("✅ Document generated successfully!", icon="📄")
        st.markdown(label)
        st.markdown(f'<div class="doc-output">{doc}</div>', unsafe_allow_html=True)
        st.download_button(
            "⬇️ Download Document (.txt)", doc,
            f"school_doc_{doc_date.strftime('%Y%m%d')}.txt", "text/plain",
            use_container_width=True)


# ═══════════════════════════════════════════════════════════
# MODULE 4 — FAST RAG TUTOR
# ═══════════════════════════════════════════════════════════
def render_rag_tutor():
    st.markdown('<div class="module-title">📚 Fast RAG Tutor</div>', unsafe_allow_html=True)
    st.markdown("**Model:** `MiniRAG-7B` · Local RAG simulation · Mock vector store · CPU-only · Zero API")
    st.markdown("---")

    st.info(
        "🗄️ **Mock Vector Store — CONNECTED**\n\n"
        "**Knowledge Base:** Grade 10 Physics — Chapter 1: Light & Reflection\n\n"
        "**Documents indexed:** 42 chunks  |  **Embedding model:** `local-minilm-sim`\n\n"
        "**Last sync:** Today at 06:00 AM  |  **Status:** 🟢 Healthy",
        icon="🔗")

    KB = {
        "real": {
            "id": "CH-014", "section": "Section 1.4 — Image Formation by Mirrors",
            "page": "Page 18–19", "sim": 0.927,
            "text": (
                "A REAL IMAGE is formed when reflected or refracted rays of light actually\n"
                "converge at a point in space. Real images CAN be projected on a screen.\n\n"
                "A concave mirror forms a real, inverted image when the object is placed\n"
                "beyond the focal point F.\n\n"
                "Key characteristics:\n"
                "  - Formed by actual intersection of reflected rays\n"
                "  - Can be caught on a screen\n"
                "  - Always inverted relative to the object\n"
                "  - Formed by concave mirrors (object > F)\n"
                "  - Mirror formula: 1/f = 1/v + 1/u"),
            "tutor": (
                "### 🔬 Real Images — Tutor Explanation\n\n"
                "Think of a **real image** like a cinema projector — the light rays *actually land on the screen*. "
                "You can literally catch it on a piece of paper!\n\n"
                "**Memory trick:** Real images are **Caught** on a screen — **C** = **Concave** mirror.\n\n"
                "**Common Exam Points:**\n"
                "- Forms only when object is placed **beyond** the focal point of a concave mirror\n"
                "- Always **inverted** (upside down)\n"
                "- Image distance v is **negative** in sign convention\n"
                "- Applications: Cinema projectors, vehicle headlights, solar furnaces"),
        },
        "virtual": {
            "id": "CH-017", "section": "Section 1.5 — Virtual Images & Convex Mirrors",
            "page": "Page 21–22", "sim": 0.904,
            "text": (
                "A VIRTUAL IMAGE is formed when reflected rays, extended backwards, appear to\n"
                "meet at a point behind the mirror. Virtual images CANNOT be projected on a screen\n"
                "because no real rays pass through the image location.\n\n"
                "A plane mirror always forms a virtual, erect, laterally inverted image.\n\n"
                "Key characteristics:\n"
                "  - Formed by apparent (extended) intersection of rays\n"
                "  - Cannot be caught on a screen\n"
                "  - Always erect (upright)\n"
                "  - Formed by plane mirrors and concave mirrors (object < F)\n"
                "  - Convex mirrors always produce virtual, erect, diminished images"),
            "tutor": (
                "### 🔮 Virtual Images — Tutor Explanation\n\n"
                "A **virtual image** is like a ghost — it *looks* like it is there, but nothing is actually at "
                "that location! Your brain traces the reflected rays backwards.\n\n"
                "**Memory trick:** Virtual images are **Visible but Not Catchable** on a screen.\n\n"
                "**Common Exam Points:**\n"
                "- Always **erect** (right-side up)\n"
                "- **Plane mirrors** → virtual, same size, laterally inverted\n"
                "- **Convex mirrors** → virtual, erect, **diminished** (always!)\n"
                "- **Concave mirrors** → virtual only when object is inside the focal point\n"
                "- Applications: Rear-view mirrors, shaving/makeup mirrors"),
        },
        "general": {
            "id": "CH-012", "section": "Section 1.3 — Concepts of Image Formation",
            "page": "Page 15–16", "sim": 0.871,
            "text": (
                "IMAGE FORMATION: Light obeys the Laws of Reflection:\n"
                "angle of incidence = angle of reflection (measured from the normal).\n\n"
                "Images are classified as:\n"
                "  1. Real or Virtual\n"
                "  2. Erect (upright) or Inverted\n"
                "  3. Magnified, Diminished, or Same Size\n\n"
                "Mirror Formula: 1/f = 1/v + 1/u\n"
                "Magnification:  m = -v/u = hi/ho"),
            "tutor": (
                "### 📐 Image Formation — Tutor Explanation\n\n"
                "Light obeys the **Laws of Reflection**: angle of incidence = angle of reflection.\n\n"
                "**The Mirror Formula (memorise this!):**\n\n"
                "$$\\frac{1}{f} = \\frac{1}{v} + \\frac{1}{u}$$\n\n"
                "**Magnification:**\n\n"
                "$$m = -\\frac{v}{u}$$\n\n"
                "- |m| > 1 → Magnified  |  |m| < 1 → Diminished  |  |m| = 1 → Same size\n"
                "- Negative m → Inverted → Real image\n"
                "- Positive m → Erect → Virtual image"),
        },
    }

    student_q = st.text_input(
        "Your Question",
        placeholder="e.g. What is a real image? How is a virtual image formed?",
        key="rag_q")
    hc, bc = st.columns([3, 1])
    with hc:
        st.caption("💡 Try: *real images*, *virtual images*, *image formation in mirrors*")
    with bc:
        ask = st.button("🧠 Ask Tutor", use_container_width=True, key="ask_btn")

    st.markdown("---")

    if ask:
        if not student_q.strip():
            st.warning("Please type a question.", icon="⚠️")
            st.stop()

        p = st.progress(0, text="MiniRAG-7B: Encoding query…")
        time.sleep(0.5)
        p.progress(30, text="Cosine-similarity search across 42 chunks…")
        time.sleep(0.6)
        p.progress(70, text="Top-k chunks retrieved. Generating response…")
        time.sleep(0.5)
        p.progress(100, text="Done.")
        time.sleep(0.2)
        p.empty()

        lq = student_q.lower()
        if "real" in lq and "virtual" not in lq:
            key = "real"
        elif "virtual" in lq:
            key = "virtual"
        elif any(k in lq for k in ["image", "mirror", "form", "reflect"]):
            key = "general"
        else:
            key = None

        if key:
            c = KB[key]
            st.markdown("#### 📥 Retrieved Context Chunk")
            st.markdown(
                f'<div class="rag-chunk">'
                f'<b>📄 Source:</b> Grade 10 Physics — Chapter 1: Light &amp; Reflection<br>'
                f'<b>📑 Section:</b> {c["section"]}  |  <b>📃 {c["page"]}</b><br>'
                f'<b>🔑 Chunk ID:</b> {c["id"]}  |  '
                f'<b>📊 Cosine Similarity:</b> <span style="color:#86efac">{c["sim"]}</span><br>'
                f'<hr style="border-color:#334155;margin:0.5rem 0">'
                f'<pre style="white-space:pre-wrap;font-family:inherit;color:#bfdbfe;margin:0">{c["text"]}</pre>'
                f'</div>',
                unsafe_allow_html=True)

            st.markdown("#### 🧑‍🏫 Tutor Explanation")
            st.markdown(c["tutor"])
            st.success("✅ RAG retrieval complete! No internet or external API was used.", icon="✅")
        else:
            st.info(
                "🤔 **Topic not found in current knowledge base**\n\n"
                "The vector store only indexes Chapter 1: Light & Reflection. "
                "Your query did not match any high-confidence chunks.\n\n"
                "**Try asking:**\n"
                "- *What is a real image?*\n"
                "- *How is a virtual image formed?*\n"
                "- *Explain image formation in a concave mirror*\n\n"
                "This will trigger the RAG retrieval pipeline!",
                icon="📖")


# ═══════════════════════════════════════════════════════════
# MAIN ROUTER
# ═══════════════════════════════════════════════════════════
def main():
    st.markdown(
        """<div style='background:linear-gradient(135deg,#1e2a50 0%,#0f1832 100%);
border:1px solid #2e3460;border-radius:14px;padding:1.4rem 2rem 1.2rem;margin-bottom:1.5rem'>
<h1 style='margin:0;font-size:1.9rem;color:#e0e7ff;font-weight:700'>
🏫 Multi-Model School Operations Console</h1>
<p style='margin:0.4rem 0 0;color:#818cf8;font-size:0.92rem'>
No-API-Key Sandbox Prototype &nbsp;·&nbsp; Powered by Local Python Rule Engines
&nbsp;·&nbsp; Designed for School Board Demonstration</p>
</div>""",
        unsafe_allow_html=True)

    active = st.session_state.get("module_select", "🎓  Admissions Predictor")
    if "Admissions" in active:
        render_admissions()
    elif "Financial" in active:
        render_financial_auditor()
    elif "Admin" in active:
        render_admin_orchestrator()
    elif "RAG" in active:
        render_rag_tutor()


if __name__ == "__main__":
    main()
